address;source_location;insn;indent
0x755ae;/usr/local/src/conda/python-3.9.19/Objects/listobject.c:969;MOV	0x8(%RSP),%RDX;
0x755b3;:0;SUB	%FS:0x28,%RDX;
0x755bc;:0;JNE	755da <list_extend.cold+0x2c>;
0x755be;:0;ADD	$0x18,%RSP;
0x755c2;:0;POP	%RBX;
0x755c3;:0;POP	%RBP;
0x755c4;/usr/local/src/conda/python-3.9.19/Objects/listobject.c:969;POP	%R12;
0x755c6;:0;POP	%R13;
0x755c8;:0;POP	%R14;
0x755ca;:0;POP	%R15;
0x755cc;:0;RET;
0x755cd;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%RBX,%RDI;
0x755d0;:0;CALL	1296a0 <_Py_Dealloc>;
0x755d5;/usr/local/src/conda/python-3.9.19/Include/object.h:430;JMP	167369 <list_extend+0x189>;
0x755da;/usr/local/src/conda/python-3.9.19/Objects/listobject.c:969;CALLQ	0x309188(%RIP);
0x755e0;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%RBX,%RDI;
0x755e3;:0;CALL	1296a0 <_Py_Dealloc>;
0x755e8;:0;JMP	1674b5 <list_extend+0x2d5>;
0x755ed;/usr/local/src/conda/python-3.9.19/Objects/listobject.c:80;CALL	2464e0 <PyErr_NoMemory>;
0x755f2;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%RBX);
0x755f5;:0;JNE	16767d <list_extend+0x49d>;
0x755fb;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%RBX,%RDI;
0x755fe;:0;CALL	1296a0 <_Py_Dealloc>;
0x75603;:0;JMP	16767d <list_extend+0x49d>;
0x75608;/usr/local/src/conda/python-3.9.19/Objects/listobject.c:80;CALL	2464e0 <PyErr_NoMemory>;
0x7560d;/usr/local/src/conda/python-3.9.19/Objects/listobject.c:80;JMP	167684 <list_extend+0x4a4>;
0x75612;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%R13);
0x75616;:0;JNE	16767d <list_extend+0x49d>;
0x7561c;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%R13,%RDI;
0x7561f;:0;CALL	1296a0 <_Py_Dealloc>;
0x75624;/usr/local/src/conda/python-3.9.19/Include/object.h:430;JMP	16767d <list_extend+0x49d>;
0x75629;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%R12,%RDI;
0x7562c;:0;CALL	1296a0 <_Py_Dealloc>;
0x75631;/usr/local/src/conda/python-3.9.19/Include/object.h:430;JMP	16746d <list_extend+0x28d>;
0x75636;/usr/local/src/conda/python-3.9.19/Objects/listobject.c:306;MOV	0x33bf7b(%RIP),%RDI;
0x7563d;:0;LEA	0x20b84c(%RIP),%RSI;
0x75644;:0;CALL	18b430 <PyErr_SetString>;
0x75649;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%R12);
0x7564d;:0;JNE	167684 <list_extend+0x4a4>;
0x75653;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%R12,%RDI;
0x75656;:0;CALL	1296a0 <_Py_Dealloc>;
0x7565b;/usr/local/src/conda/python-3.9.19/Include/object.h:430;JMP	167684 <list_extend+0x4a4>;
