address;source_location;insn;indent
0x16c040;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:509;PUSH	%R12;
0x16c042;:0;PUSH	%RBP;
0x16c043;:0;MOV	%RSI,%RBP;
0x16c046;:0;PUSH	%RBX;
0x16c047;:0;MOV	%RDI,%RBX;
0x16c04a;:0;SUB	$0x10,%RSP;
0x16c04e;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:510;MOV	0x10(%RSI),%R12;
0x16c052;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:509;MOV	%FS:0x28,%RAX;
0x16c05b;:0;MOV	%RAX,0x8(%RSP);
0x16c060;:0;XOR	%EAX,%EAX;
0x16c062;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:64;TEST	%RDX,%RDX;
0x16c065;:0;JNE	77353 <StopIteration_init.cold+0x3b>;
0x16c06b;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:68;MOV	0x18(%RDI),%RDI;
0x16c06f;/usr/local/src/conda/python-3.9.19/Include/object.h:408;INCQ	(%RSI);
0x16c072;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:68;MOV	%RSI,0x18(%RBX);
0x16c076;/usr/local/src/conda/python-3.9.19/Include/object.h:496;TEST	%RDI,%RDI;
0x16c079;:0;JE	16c0c7 <StopIteration_init+0x87>;
0x16c07b;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%RDI);
0x16c07e;:0;JE	77318 <StopIteration_init.cold>;
0x16c084;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:515;MOV	0x40(%RBX),%RDI;
0x16c088;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:515;TEST	%RDI,%RDI;
0x16c08b;:0;JNE	16c0c2 <StopIteration_init+0x82>;
0x16c08d;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:516;TEST	%R12,%R12;
0x16c090;:0;JLE	77347 <StopIteration_init.cold+0x2f>;
0x16c096;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:517;MOV	0x18(%RBP),%RAX;
0x16c09a;/usr/local/src/conda/python-3.9.19/Include/object.h:408;INCQ	(%RAX);
0x16c09d;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:521;MOV	%RAX,0x40(%RBX);
0x16c0a1;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;XOR	%EAX,%EAX;
0x16c0a3;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;MOV	0x8(%RSP),%RDX;
0x16c0a8;:0;SUB	%FS:0x28,%RDX;
0x16c0b1;:0;JNE	16c0bc <StopIteration_init+0x7c>;
0x16c0b3;:0;ADD	$0x10,%RSP;
0x16c0b7;:0;POP	%RBX;
0x16c0b8;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;POP	%RBP;
0x16c0b9;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;POP	%R12;
0x16c0bb;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;RET;
0x16c0bc;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;CALLQ	0x2126a6(%RIP);
0x16c0c2;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;JMP	7732a <StopIteration_init.cold+0x12>;
0x16c0c7;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;JMP	7731d <StopIteration_init.cold+0x5>;
0x16c0cc;/usr/local/src/conda/python-3.9.19/Objects/exceptions.c:523;NOPL	(%RAX);
