address;source_location;insn;indent
0x53a108;/usr/local/src/conda/python-3.12.0/Modules/gcmodule.c:490;MOV	0x18(%RBX),%RAX;
0x53a10c;/usr/local/src/conda/python-3.12.0/Modules/gcmodule.c:489;LEA	0x10(%RBX),%RDI;
0x53a110;/usr/local/src/conda/python-3.12.0/Modules/gcmodule.c:491;MOV	$0x53a4d0,%ESI;
0x53a115;/usr/local/src/conda/python-3.12.0/Modules/gcmodule.c:491;MOV	%RDI,%RDX;
0x53a118;/usr/local/src/conda/python-3.12.0/Modules/gcmodule.c:491;CALLQ	0xb8(%RAX);
0x53a11e;/usr/local/src/conda/python-3.12.0/Include/internal/pycore_gc.h:60;MOV	(%RBX),%RBX;
0x53a121;/usr/local/src/conda/python-3.12.0/Modules/gcmodule.c:488;CMP	%RBX,%RBP;
0x53a124;/usr/local/src/conda/python-3.12.0/Modules/gcmodule.c:488;JNE	53a108 <deduce_unreachable+0xa8>;
