/usr/local/src/conda/python-3.9.19/Objects/dictobject.c: 2126 - 2128
--------------------------------------------------------------------------------

