/usr/local/src/conda/python-3.9.19/Objects/exceptions.c: 64 - 68
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Objects/exceptions.c: 509 - 523
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Include/object.h: 408 - 408
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Include/object.h: 422 - 422
--------------------------------------------------------------------------------

/usr/local/src/conda/python-3.9.19/Include/object.h: 496 - 496
--------------------------------------------------------------------------------

