address;source_location;insn;indent
0x501a00;/usr/local/src/conda/python-3.9.19/Python/errors.c:70;PUSH	%R12;
0x501a02;:0;MOVQ	%RDI,%XMM0;
0x501a07;:0;MOVQ	%RSI,%XMM1;
0x501a0c;:0;PUSH	%RBP;
0x501a0d;:0;PUNPCKLQDQ	%XMM1,%XMM0;
0x501a11;/usr/local/src/conda/python-3.9.19/Python/errors.c:70;PUSH	%RBX;
0x501a12;:0;SUB	$0x10,%RSP;
0x501a16;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	0x24653b(%RIP),%RBX;
0x501a1d;/usr/local/src/conda/python-3.9.19/Python/errors.c:46;TEST	%RDX,%RDX;
0x501a20;:0;JNE	501a5a <PyErr_Restore+0x5a>;
0x501a22;/usr/local/src/conda/python-3.9.19/Python/errors.c:70;XOR	%EDX,%EDX;
0x501a24;/usr/local/src/conda/python-3.9.19/Python/errors.c:55;MOV	0x58(%RBX),%RDI;
0x501a28;/usr/local/src/conda/python-3.9.19/Python/errors.c:56;MOV	0x60(%RBX),%RBP;
0x501a2c;/usr/local/src/conda/python-3.9.19/Python/errors.c:59;MOVUPS	%XMM0,0x58(%RBX);
0x501a30;/usr/local/src/conda/python-3.9.19/Python/errors.c:57;MOV	0x68(%RBX),%R12;
0x501a34;/usr/local/src/conda/python-3.9.19/Python/errors.c:61;MOV	%RDX,0x68(%RBX);
0x501a38;/usr/local/src/conda/python-3.9.19/Include/object.h:496;TEST	%RDI,%RDI;
0x501a3b;:0;JNE	501a50 <PyErr_Restore+0x50>;
0x501a3d;/usr/local/src/conda/python-3.9.19/Include/object.h:496;TEST	%RBP,%RBP;
0x501a40;:0;JNE	501a6e <PyErr_Restore+0x6e>;
0x501a42;/usr/local/src/conda/python-3.9.19/Include/object.h:496;TEST	%R12,%R12;
0x501a45;:0;JNE	501a80 <PyErr_Restore+0x80>;
0x501a47;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;ADD	$0x10,%RSP;
0x501a4b;:0;POP	%RBX;
0x501a4c;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;POP	%RBP;
0x501a4d;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;POP	%R12;
0x501a4f;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;RET;
0x501a50;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%RDI);
0x501a53;:0;JNE	501a3d <PyErr_Restore+0x3d>;
0x501a55;:0;JMP	431fa7 <PyErr_Restore.cold>;
0x501a5a;/usr/local/src/conda/python-3.9.19/Python/errors.c:46;CMPQ	$0x732180,0x8(%RDX);
0x501a62;:0;JE	501a24 <PyErr_Restore+0x24>;
0x501a64;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%RDX);
0x501a67;:0;JNE	501a22 <PyErr_Restore+0x22>;
0x501a69;:0;JMP	431fba <PyErr_Restore.cold+0x13>;
0x501a6e;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%RBP);
0x501a72;:0;JNE	501a42 <PyErr_Restore+0x42>;
0x501a74;/usr/local/src/conda/python-3.9.19/Objects/object.c:2205;MOV	0x8(%RBP),%RAX;
0x501a78;/usr/local/src/conda/python-3.9.19/Objects/object.c:2209;MOV	%RBP,%RDI;
0x501a7b;:0;CALLQ	0x30(%RAX);
0x501a7e;/usr/local/src/conda/python-3.9.19/Objects/object.c:2210;JMP	501a42 <PyErr_Restore+0x42>;
0x501a80;/usr/local/src/conda/python-3.9.19/Include/object.h:422;DECQ	(%R12);
0x501a84;:0;JNE	501a47 <PyErr_Restore+0x47>;
0x501a86;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;ADD	$0x10,%RSP;
0x501a8a;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%R12,%RDI;
0x501a8d;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;POP	%RBX;
0x501a8e;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;POP	%RBP;
0x501a8f;/usr/local/src/conda/python-3.9.19/Python/errors.c:73;POP	%R12;
0x501a91;/usr/local/src/conda/python-3.9.19/Include/object.h:430;JMP	4d6450 <_Py_Dealloc>;
0x501a96;/usr/local/src/conda/python-3.9.19/Include/object.h:430;NOPW	%CS:(%RAX,%RAX,1);
