/usr/local/src/conda/python-3.9.19/Objects/listobject.c: 282 - 283
--------------------------------------------------------------------------------

