/usr/local/src/conda/python-3.9.19/Objects/setobject.c: 456 - 458
--------------------------------------------------------------------------------

