/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_pyerrors.h: 23 - 23
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 220 - 220
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 234 - 234
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 243 - 243
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 701 - 706
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/object.h: 967 - 969
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_call.h: 44 - 44
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_call.h: 53 - 53
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/./Include/internal/pycore_call.h: 88 - 93
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Objects/call.c: 14 - 15
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Objects/call.c: 523 - 523
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Objects/call.c: 530 - 550
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Objects/call.c: 557 - 557
--------------------------------------------------------------------------------

/tmp/python-build.20240827235536.29272/Python-3.12.0/Objects/call.c: 566 - 573
--------------------------------------------------------------------------------

