address;source_location;insn;indent
0x6ffbd;/usr/local/src/conda/python-3.9.19/Objects/frameobject.c:39;MOV	0x6c(%RDI),%EDX;
0x6ffc0;/usr/local/src/conda/python-3.9.19/Objects/frameobject.c:42;MOV	0x68(%RDI),%EDI;
0x6ffc3;/usr/local/src/conda/python-3.9.19/Objects/frameobject.c:42;JMP	157643 <PyTraceBack_Here+0x443>;
0x6ffc8;/usr/local/src/conda/python-3.9.19/Python/traceback.c:43;MOV	$0x2b,%ESI;
0x6ffcd;:0;LEA	0x213014(%RIP),%RDI;
0x6ffd4;:0;MOVAPS	%XMM0,(%RSP);
0x6ffd8;/usr/local/src/conda/python-3.9.19/Python/traceback.c:43;CALL	d9689 <_PyErr_BadInternalCall>;
0x6ffdd;/usr/local/src/conda/python-3.9.19/Python/traceback.c:44;MOVDQA	(%RSP),%XMM0;
0x6ffe2;/usr/local/src/conda/python-3.9.19/Python/traceback.c:248;MOVHLPS	%XMM0,%XMM6;
0x6ffe5;:0;MOVQ	%XMM0,%RDI;
0x6ffea;:0;MOV	%R12,%RDX;
0x6ffed;:0;MOVQ	%XMM6,%RSI;
0x6fff2;:0;CALL	1fc160 <_PyErr_ChainExceptions>;
0x6fff7;/usr/local/src/conda/python-3.9.19/Python/traceback.c:249;OR	$-0x1,%EAX;
0x6fffa;/usr/local/src/conda/python-3.9.19/Python/traceback.c:254;MOV	0x38(%RSP),%RDX;
0x6ffff;:0;SUB	%FS:0x28,%RDX;
0x70008;:0;JNE	7004f <PyTraceBack_Here.cold+0x92>;
0x7000a;:0;ADD	$0x40,%RSP;
0x7000e;:0;POP	%RBX;
0x7000f;:0;POP	%RBP;
0x70010;:0;POP	%R12;
0x70012;:0;POP	%R13;
0x70014;:0;POP	%R14;
0x70016;:0;RET;
0x70017;/usr/local/src/conda/python-3.9.19/Objects/object.c:1825;MOV	%R14,%RDI;
0x7001a;:0;MOVAPS	%XMM0,0x10(%RSP);
0x7001f;:0;MOVQ	%XMM2,(%RSP);
0x70024;:0;CALL	e8a37 <_PyTraceMalloc_NewReference>;
0x70029;:0;MOVQ	(%RSP),%XMM2;
0x7002e;:0;MOVDQA	0x10(%RSP),%XMM0;
0x70034;:0;JMP	157501 <PyTraceBack_Here+0x301>;
0x70039;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%R14,%RDI;
0x7003c;:0;MOVAPS	%XMM0,(%RSP);
0x70040;:0;CALL	1296a0 <_Py_Dealloc>;
0x70045;:0;MOVDQA	(%RSP),%XMM0;
0x7004a;:0;JMP	157786 <PyTraceBack_Here+0x586>;
0x7004f;/usr/local/src/conda/python-3.9.19/Python/traceback.c:254;CALLQ	0x30e713(%RIP);
0x70055;/usr/local/src/conda/python-3.9.19/Python/traceback.c:254;MOV	%R14,%RDI;
0x70058;:0;CALL	63bc2 <PyObject_GC_Track.part.0>;
0x7005d;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%R12,%RDI;
0x70060;:0;CALL	1296a0 <_Py_Dealloc>;
0x70065;:0;JMP	1575b9 <PyTraceBack_Here+0x3b9>;
0x7006a;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2270;MOV	%R14,%RDI;
0x7006d;:0;MOVAPS	%XMM0,0x10(%RSP);
0x70072;:0;MOVQ	%XMM2,(%RSP);
0x70077;:0;CALL	246520 <_PyErr_NoMemory>;
0x7007c;:0;MOVQ	(%RSP),%XMM2;
0x70081;:0;MOVDQA	0x10(%RSP),%XMM0;
0x70087;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2270;MOV	%RAX,%R14;
0x7008a;/usr/local/src/conda/python-3.9.19/Modules/gcmodule.c:2307;TEST	%RAX,%RAX;
0x7008d;:0;JNE	1574db <PyTraceBack_Here+0x2db>;
0x70093;:0;JMP	6ffe2 <PyTraceBack_Here.cold+0x25>;
0x70098;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1200;MOV	0x18(%RDX),%RDX;
0x7009c;:0;MOV	0x344b5d(%RIP),%RDI;
0x700a3;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1200;XOR	%EAX,%EAX;
0x700a5;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1200;MOVAPS	%XMM0,(%RSP);
0x700a9;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1200;LEA	0x22c894(%RIP),%R13;
0x700b0;:0;MOV	%R13,%RSI;
0x700b3;:0;CALL	153de0 <PyErr_Format>;
0x700b8;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1210;MOV	0x78(%RBX),%RAX;
0x700bc;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1210;MOVDQA	(%RSP),%XMM0;
0x700c1;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1210;MOV	0x8(%RAX),%RAX;
0x700c5;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1210;TESTB	$0x8,0xab(%RAX);
0x700cc;:0;JE	700ef <PyTraceBack_Here.cold+0x132>;
0x700ce;/usr/local/src/conda/python-3.9.19/Python/traceback.c:236;MOV	0x68(%RBP),%EDI;
0x700d1;/usr/local/src/conda/python-3.9.19/Objects/codeobject.c:995;MOV	0x28(%RBX),%EDX;
0x700d4;/usr/local/src/conda/python-3.9.19/Objects/codeobject.c:995;JMP	157643 <PyTraceBack_Here+0x443>;
0x700d9;/usr/local/src/conda/python-3.9.19/Include/object.h:430;MOV	%RAX,%RDI;
0x700dc;:0;CALL	1296a0 <_Py_Dealloc>;
0x700e1;/usr/local/src/conda/python-3.9.19/Include/object.h:496;TEST	%RBP,%RBP;
0x700e4;:0;JNE	15768c <PyTraceBack_Here+0x48c>;
0x700ea;:0;JMP	1575a7 <PyTraceBack_Here+0x3a7>;
0x700ef;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1211;MOV	0x18(%RAX),%RDX;
0x700f3;:0;MOV	0x344b06(%RIP),%RDI;
0x700fa;:0;MOV	%R13,%RSI;
0x700fd;:0;XOR	%EAX,%EAX;
0x700ff;:0;MOVAPS	%XMM0,(%RSP);
0x70103;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1211;CALL	153de0 <PyErr_Format>;
0x70108;/usr/local/src/conda/python-3.9.19/Python/traceback.c:236;MOV	0x68(%RBP),%EDI;
0x7010b;/usr/local/src/conda/python-3.9.19/Objects/bytesobject.c:1213;MOVDQA	(%RSP),%XMM0;
0x70110;:0;JMP	700d1 <PyTraceBack_Here.cold+0x114>;
