address;source_location;insn;indent
0x156e40;/usr/local/src/conda/python-3.9.19/Python/errors.c:299;PUSH	%R13;
0x156e42;:0;PUSH	%R12;
0x156e44;:0;PUSH	%RBP;
0x156e45;:0;PUSH	%RBX;
0x156e46;:0;SUB	$0x18,%RSP;
0x156e4a;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pystate.h:55;MOV	%FS:0x28,%RAX;
0x156e53;:0;MOV	%RAX,0x8(%RSP);
0x156e58;:0;MOV	0x25f099(%RIP),%RAX;
0x156e5f;/usr/local/src/conda/python-3.9.19/Include/internal/pycore_pyerrors.h:14;MOV	0x58(%RAX),%RBP;
0x156e63;/usr/local/src/conda/python-3.9.19/Python/errors.c:261;TEST	%RBP,%RBP;
0x156e66;:0;JE	156f30 <PyErr_ExceptionMatches+0xf0>;
0x156e6c;:0;MOV	%RDI,%RBX;
0x156e6f;:0;TEST	%RDI,%RDI;
0x156e72;:0;JE	156f30 <PyErr_ExceptionMatches+0xf0>;
0x156e78;/usr/local/src/conda/python-3.9.19/Include/object.h:628;MOV	0x8(%RDI),%RAX;
0x156e7c;/usr/local/src/conda/python-3.9.19/Include/object.h:628;MOV	0xa8(%RAX),%RAX;
0x156e83;/usr/local/src/conda/python-3.9.19/Python/errors.c:265;TEST	$0x4000000,%EAX;
0x156e88;:0;JNE	156f57 <PyErr_ExceptionMatches+0x117>;
0x156e8e;/usr/local/src/conda/python-3.9.19/Python/errors.c:279;MOV	0x8(%RBP),%RCX;
0x156e92;/usr/local/src/conda/python-3.9.19/Include/object.h:628;MOV	0xa8(%RCX),%RDX;
0x156e99;/usr/local/src/conda/python-3.9.19/Python/errors.c:279;TEST	$0x40000000,%EDX;
0x156e9f;:0;JNE	156f83 <PyErr_ExceptionMatches+0x143>;
0x156ea5;/usr/local/src/conda/python-3.9.19/Python/errors.c:282;TEST	$-0x80000000,%EDX;
0x156eab;:0;JE	6ff8b <PyErr_ExceptionMatches.cold+0x3>;
0x156eb1;/usr/local/src/conda/python-3.9.19/Python/errors.c:282;TESTB	$0x40,0xab(%RBP);
0x156eb8;:0;JE	6ff8b <PyErr_ExceptionMatches.cold+0x3>;
0x156ebe;/usr/local/src/conda/python-3.9.19/Python/errors.c:282;TEST	$-0x80000000,%EAX;  (1283) 
0x156ec3;:0;JE	6ff8b <PyErr_ExceptionMatches.cold+0x3>;  (1283) 
0x156ec9;/usr/local/src/conda/python-3.9.19/Python/errors.c:282;TESTB	$0x40,0xab(%RBX);  (1283) 
0x156ed0;:0;JE	6ff8b <PyErr_ExceptionMatches.cold+0x3>;  (1283) 
0x156ed6;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1425;MOV	0x158(%RBP),%RAX;  (1283) 
0x156edd;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1426;TEST	%RAX,%RAX;  (1283) 
0x156ee0;:0;JE	156f9c <PyErr_ExceptionMatches+0x15c>;  (1283) 
0x156ee6;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1431;MOV	0x10(%RAX),%RDX;  (1283) 
0x156eea;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1432;TEST	%RDX,%RDX;  (1283) 
0x156eed;:0;JLE	156f30 <PyErr_ExceptionMatches+0xf0>;  (1283) 
0x156eef;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1433;CMP	0x18(%RAX),%RBX;  (1283) 
0x156ef3;:0;JE	156f50 <PyErr_ExceptionMatches+0x110>;  (1283) 
0x156ef5;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1432;CMP	$0x1,%RDX;  (1283) 
0x156ef9;:0;JE	156f30 <PyErr_ExceptionMatches+0xf0>;  (1283) 
0x156efb;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1433;CMP	0x20(%RAX),%RBX;  (1283) 
0x156eff;:0;JE	156f50 <PyErr_ExceptionMatches+0x110>;  (1283) 
0x156f01;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1432;CMP	$0x2,%RDX;  (1283) 
0x156f05;:0;JE	156f30 <PyErr_ExceptionMatches+0xf0>;  (1283) 
0x156f07;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1433;CMP	0x28(%RAX),%RBX;  (1283) 
0x156f0b;:0;JE	156f50 <PyErr_ExceptionMatches+0x110>;  (1283) 
0x156f0d;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1432;CMP	$0x3,%RDX;  (1283) 
0x156f11;:0;JE	156f30 <PyErr_ExceptionMatches+0xf0>;  (1283) 
0x156f13;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1432;MOV	$0x3,%ECX;  (1283) 
0x156f18;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1433;CMP	0x18(%RAX,%RCX,8),%RBX;    (1286) 
0x156f1d;:0;JE	156f50 <PyErr_ExceptionMatches+0x110>;    (1286) 
0x156f1f;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1432;INC	%RCX;    (1286) 
0x156f22;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1432;CMP	%RCX,%RDX;    (1286) 
0x156f25;:0;JNE	156f18 <PyErr_ExceptionMatches+0xd8>;    (1286) 
0x156f27;:0;NOPW	(%RAX,%RAX,1);(1285) 
0x156f30;/usr/local/src/conda/python-3.9.19/Python/errors.c:301;XOR	%EAX,%EAX;(1285) 
0x156f32;/usr/local/src/conda/python-3.9.19/Python/errors.c:302;MOV	0x8(%RSP),%RDX;  (1283) 
0x156f37;:0;SUB	%FS:0x28,%RDX;  (1283) 
0x156f40;:0;JNE	156f7d <PyErr_ExceptionMatches+0x13d>;  (1283) 
0x156f42;:0;ADD	$0x18,%RSP;
0x156f46;:0;POP	%RBX;
0x156f47;:0;POP	%RBP;
0x156f48;:0;POP	%R12;
0x156f4a;:0;POP	%R13;
0x156f4c;:0;RET;
0x156f4d;:0;NOPL	(%RAX);
0x156f50;/usr/local/src/conda/python-3.9.19/Python/errors.c:301;MOV	$0x1,%EAX;  (1283) 
0x156f55;:0;JMP	156f32 <PyErr_ExceptionMatches+0xf2>;  (1283) 
0x156f57;/usr/local/src/conda/python-3.9.19/Python/errors.c:267;CALL	1436d0 <PyTuple_Size>;
0x156f5c;/usr/local/src/conda/python-3.9.19/Python/errors.c:268;XOR	%R12D,%R12D;
0x156f5f;/usr/local/src/conda/python-3.9.19/Python/errors.c:267;MOV	%RAX,%R13;
0x156f62;/usr/local/src/conda/python-3.9.19/Python/errors.c:268;CMP	%R12,%R13;(1287) 
0x156f65;:0;JLE	156f30 <PyErr_ExceptionMatches+0xf0>;(1287) 
0x156f67;/usr/local/src/conda/python-3.9.19/Python/errors.c:270;MOV	0x18(%RBX,%R12,8),%RSI;(1287) 
0x156f6c;:0;MOV	%RBP,%RDI;(1287) 
0x156f6f;:0;CALL	157010 <PyErr_GivenExceptionMatches>;(1287) 
0x156f74;/usr/local/src/conda/python-3.9.19/Python/errors.c:270;TEST	%EAX,%EAX;(1287) 
0x156f76;:0;JNE	156f50 <PyErr_ExceptionMatches+0x110>;(1287) 
0x156f78;/usr/local/src/conda/python-3.9.19/Python/errors.c:268;INC	%R12;(1287) 
0x156f7b;/usr/local/src/conda/python-3.9.19/Python/errors.c:268;JMP	156f62 <PyErr_ExceptionMatches+0x122>;(1287) 
0x156f7d;/usr/local/src/conda/python-3.9.19/Python/errors.c:302;CALLQ	0x2277e5(%RIP);  (1283) 
0x156f83;/usr/local/src/conda/python-3.9.19/Include/object.h:628;MOV	0x8(%RCX),%RDX;  (1283) 
0x156f87;/usr/local/src/conda/python-3.9.19/Python/errors.c:282;TESTB	$-0x80,0xab(%RDX);  (1283) 
0x156f8e;:0;JE	6ff88 <PyErr_ExceptionMatches.cold>;  (1283) 
0x156f94;/usr/local/src/conda/python-3.9.19/Include/object.h:630;MOV	%RCX,%RBP;  (1283) 
0x156f97;:0;JMP	156ebe <PyErr_ExceptionMatches+0x7e>;  (1283) 
0x156f9c;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1412;CMP	%RBP,%RBX;    (1284) 
0x156f9f;:0;JE	156f50 <PyErr_ExceptionMatches+0x110>;    (1284) 
0x156fa1;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1414;MOV	0x100(%RBP),%RBP;    (1284) 
0x156fa8;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1415;TEST	%RBP,%RBP;    (1284) 
0x156fab;:0;JNE	156f9c <PyErr_ExceptionMatches+0x15c>;    (1284) 
0x156fad;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1417;LEA	0x24fdac(%RIP),%RAX;  (1283) 
0x156fb4;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1417;CMP	%RAX,%RBX;  (1283) 
0x156fb7;:0;SETE	%AL;  (1283) 
0x156fba;:0;MOVZX	%AL,%EAX;  (1283) 
0x156fbd;:0;JMP	156f32 <PyErr_ExceptionMatches+0xf2>;  (1283) 
0x156fc2;/usr/local/src/conda/python-3.9.19/Objects/typeobject.c:1417;NOPW	%CS:(%RAX,%RAX,1);
0x156fcd;:0;NOPL	(%RAX);
